// <auto-generated />
using System;
using BTCPayServer.Plugins.BTCMap;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.Plugins.BTCMap.Migrations
{
    [DbContext(typeof(BtcMapDbContext))]
    partial class BtcMapDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.Plugins.BTCMap")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTCPayServer.Plugins.BTCMap.Data.BtcMapListing", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("AcceptsLightning")
                        .HasColumnType("boolean");

                    b.Property<string>("BusinessName")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DirectorySubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DirectorySubmittedUrl")
                        .HasColumnType("text");

                    b.Property<string>("DirectoryPrUrl")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Twitter")
                        .HasColumnType("text");

                    b.Property<string>("Github")
                        .HasColumnType("text");

                    b.Property<string>("OnionUrl")
                        .HasColumnType("text");

                    b.Property<string>("DirectoryType")
                        .HasColumnType("text");

                    b.Property<string>("DirectorySubType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<long>("OsmElementId")
                        .HasColumnType("bigint");

                    b.Property<string>("OsmElementType")
                        .HasColumnType("text");

                    b.Property<int>("OsmElementVersion")
                        .HasColumnType("integer");

                    b.Property<string>("PostCode")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StoreId")
                        .IsUnique();

                    b.HasIndex("Status", "LastVerifiedAt");

                    b.ToTable("Listings", "BTCPayServer.Plugins.BTCMap");
                });
#pragma warning restore 612, 618
        }
    }
}
